### ISSUE TITLE
help

### ISSUE THREAD

**Issue by rafix8989** [kuriatsu/joy_teleop#1]
Hello, I have a donkey car , I installed ROS kinetic on it, I can control it from my laptop using a gamepad, but I would like to use the g29 steering wheel, will you help?

**Comment by kuriatsu** [comment]
You can use it if you are using ros-kinetic-joy package.
It's like plug-and-play.
Remember you should use it with ps3 mode.

**Comment by rafix8989** [comment]
I have a problem with the i2c controller I do not want to work, I would give you access to the raspberry vnc would you see?
it's not a job to earn money, it's a toy for the son

**Comment by kuriatsu** [comment]
I don't understand why you using i2c controller for the G29 steering wheel.
Is there any interface for i2c on G29?

**Comment by rafix8989** [comment]
I use the i2c controller to control the ESC and servo of an rc car with raspberry pi 4. I have G29 connected to my laptop, Raspberry pi 4  is connected via wifi
Ubuntu is on raspberry pi 4  and ubuntu is on laptop

**Comment by rafix8989** [comment]
I can't find the tutorial for auto rc remote control via wifi with steering wheel.
I'm just learning ROS
I am using the i2c controller
 PCA9685

**Comment by kuriatsu** [comment]
Are you using joy node provided by ros-kinetic-joy which read joystick (gamepad/G29 etc.) input and convert to ros msg?
If so, the shape of the msg for G29 is different from the gamepad. 
I'm not sure that these problems are caused by i2c connection.
And I'm not familiar with i2c controller.

**Comment by rafix8989** [comment]
I'm using it
https://www.youtube.com/watch?v=z2FLrzj3330
 I also have an arduino. I do not know how to convert it to steering wheels does not work well roslaunch with steering wheel

**Comment by rafix8989** [comment]
``<launch>
  

  <node pkg="jetsoncar_teleop" type="jetsoncar_teleop_joy" name="jetsoncar_teleop_joystick">
    <param name="scale_angular" value="1.0"/>
    <param name="scale_linear" value="0.5"/>
    
    <param name="axis_deadman" value="4"/>
    
    <param name="axis_linear" value="4"/>
    <param name="axis_angular" value="0"/>

    <param name="button_a" value="0"/>
    <param name="button_b" value="1"/>
    <param name="button_x" value="3"/>
    
    
    <param name="button_left" value="6"/>
    <param name="button_right" value="7"/>

  </node>

  <node pkg="joy" type="joy_node" name="joystick" >
    <param name="deadzone" value="0.0" />
  </node>

</launch>

**Comment by kuriatsu** [comment]
I think you need to change 'value' referring to value you can get with 
`rosrun joy joy_node` 
then 
`rostopic echo /joy`
But it depends on source code.

**Comment by kuriatsu** [comment]
/joy message has list for input.
And the values in roslaunch is corresponding to it.

gamepad and g29 has different list (shape), so you need to modify it.

**Comment by rafix8989** [comment]
I don't know how much you want for your help or you can't?

**Comment by rafix8989** [comment]
I will give you a server vnc laptop ubuntu will you try to convert?

**Comment by kuriatsu** [comment]
Can I take a look at your code for the conversion?
It's better for me.

**Comment by rafix8989** [comment]
are you on some website where you can write faster?
I will send you in a moment

**Comment by kuriatsu** [comment]
If you uploaded it on github, I can check it.

**Comment by rafix8989** [comment]
https://drive.google.com/drive/folders/1JBtb8kVFr53RBSEAj_MISPKb3xrj53hj?usp=sharing 
I threw the entire katalok

**Comment by kuriatsu** [comment]
OK, I understand.

> gamepad and g29 has different list (shape), so you need to modify it.

may be correct solution if your gamepad works well.

**Comment by kuriatsu** [comment]
You can type `rostopic echo /joy ` on terminal while running the other programs.
You can get the message when you push any buttons or rotate the steering.
Then check the index of the list (axis[0, 0, ...], and buttons[0,0,1,0,...]) in message.
Change the parameters in the .launch file because the original one is for gamepad, you need to change them for g29.
The 'value' of parameters means the index of the list.

**Comment by rafix8989** [comment]
I can't change the roslaunch to
G29 without pressing the Y button

**Comment by kuriatsu** [comment]
Can you edit nyko_teleop.launch in your editor?

**Comment by rafix8989** [comment]
I can in nano
I made various changes but I have to press the button to publish. And I want to turn and press the gas and brake

**Comment by kuriatsu** [comment]
Can you check the message by `rostopic echo /joy`?
And check which index was changed by pushing and rotating.

**Comment by rafix8989** [comment]
so is the data

**Comment by rafix8989** [comment]
raspberry pi4 i see

rostopic list
/diagnostics
/jetsoncar_teleop_joystick/cmd_vel
/joy
/joy/set_feedback
/rosout
/rosout_agg

**Comment by rafix8989** [comment]
how to change it to arduino pwm or i2c controler pwm?

**Comment by rafix8989** [comment]
I use to receive messages on raspberry pi4
rosserial python serial_node.py

which connects via usb to arduino

**Comment by kuriatsu** [comment]
You can change nyko_teleop.launch.
My understanding is that G29 is connected to your laptop and you run nyko_teleop.launch in pi4, right?
So you can type `rostopic echo /joy` on your laptop and see the message.

**Comment by kuriatsu** [comment]
Or you can type `rostopic echo /joy` on pi4.
Then, change nyko_teleop.launch according to the message.

**Comment by kuriatsu** [comment]
<param name="axis_deadman" value="1"/> <- change value to the index of /joy buttons[] when you push Y button -> 
    <param name="axis_linear" value="2"/> <- It may be correct for G29. Push gas pedal for Throttle.  ->
    <param name="axis_angular" value="0"/> <- It may be correct for G29. Rotate wheel for steering.  ->

    <param name="button_a" value="0"/> <- change value to the index of /joy buttons[] when you push A button -> 
    <param name="button_b" value="1"/> <- change value to the index of /joy buttons[] when you push B button ->
    <param name="button_x" value="3"/> <- change value to the index of /joy buttons[] when you push X button ->

    <param name="button_left" value="6"/> <- Is it for steering? I'm not sure. It depends on the model of the controller ->
    <param name="button_right" value="7"/> <- Is it for steering? I'm not sure. It depends on the model of the controller ->

**Comment by rafix8989** [comment]
yes G29 connected to laptop
I see the news on pi4 and on a laptop

**Comment by rafix8989** [comment]
and the code is whole because git here can cut the code to reduce the display?

**Comment by rafix8989** [comment]
the one that I see on the page has 8 lines

**Comment by kuriatsu** [comment]
It's part of  nyko_teleop.launch.
Please use it just as as reference.

**Comment by rafix8989** [comment]
it works to send data when the button is pressed.
And you can send the data without pressing the publish button 
?

**Comment by rafix8989** [comment]
in 2 hours checks on rc car how it works

**Comment by kuriatsu** [comment]
> And you can send the data without pressing the publish button
You can generate the same message by typing
`$ rostopic pub /joy ....`.
But pushing a button is much easier.

**Comment by rafix8989** [comment]
I tested by pressing the gas, the car goes slower, you do not need to change the joy.cpp file? How to add a brake, and how to add a direction change button

**Comment by rafix8989** [comment]
as soon as I press the publish button, the car starts moving without pressing the gas

**Comment by kuriatsu** [comment]
What is the `publish button`? I don't know it.
I think you can change direction by rotating the steering wheel.
Was there a brake button when you used the gamepad?

**Comment by rafix8989** [comment]
I mean holding the deadman button.
Orward and reverse driving direction, i.e. the corresponding impulse 1 ms forward 1.5 ms neutral 2 ms back.
Braking was not because it did not want to work as it should on the gamepad, unfortunately

**Comment by kuriatsu** [comment]
I see.
As you know, you need to rotate the steering wheel or push the gas pedal while pushing the deadman button.
While releasing the deadman button, the steer and speed will be set to zero.

**Comment by kuriatsu** [comment]
If you wanna add brake, you need to modify joy.cpp.
It's not so complicated, it's almost the same code with accel (`vel.linear.x` part in joy.cpp)
